import ReactECharts from "echarts-for-react";
import DashboardTable from "../Dashboard/DashboardTable";
import ThailandDeath from "../Dashboard/thailand-death-cause.json";
const mockData = [
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 53,
    causeOfDeath: "มะเร็ง และเนื้องอกทุกชนิด",
    year: 2557,
    deathMale: 384,
    deathFemale: 284,
    deathRatePer100000MalePopulation: 123.2,
    deathRatePer100000FemalePopulation: 89.1,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 116,
    causeOfDeath: "อุบัติเหตุจากการขนส่ง",
    year: 2557,
    deathMale: 104,
    deathFemale: 24,
    deathRatePer100000MalePopulation: 33.4,
    deathRatePer100000FemalePopulation: 7.5,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 29,
    causeOfDeath: "ความดันเลือดสูง",
    year: 2557,
    deathMale: 22,
    deathFemale: 28,
    deathRatePer100000MalePopulation: 7.1,
    deathRatePer100000FemalePopulation: 8.8,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 90,
    causeOfDeath: "โรคหลอดเลือดในสมอง",
    year: 2557,
    deathMale: 195,
    deathFemale: 141,
    deathRatePer100000MalePopulation: 62.5,
    deathRatePer100000FemalePopulation: 44.2,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 93,
    causeOfDeath: "โรคหัวใจขาดเลือด",
    year: 2557,
    deathMale: 184,
    deathFemale: 141,
    deathRatePer100000MalePopulation: 59,
    deathRatePer100000FemalePopulation: 44.2,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 48,
    causeOfDeath: "ปอดอักเสบและโรคอื่นๆ ของปอด",
    year: 2557,
    deathMale: 270,
    deathFemale: 200,
    deathRatePer100000MalePopulation: 86.6,
    deathRatePer100000FemalePopulation: 62.7,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 5,
    causeOfDeath: "ไตอักเสบ กลุ่มอาการของไตพิการ และไตพิการ",
    year: 2557,
    deathMale: 57,
    deathFemale: 53,
    deathRatePer100000MalePopulation: 18.3,
    deathRatePer100000FemalePopulation: 16.6,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 10,
    causeOfDeath: "โรคเกี่ยวกับตับและตับอ่อน",
    year: 2557,
    deathMale: 73,
    deathFemale: 50,
    deathRatePer100000MalePopulation: 23.4,
    deathRatePer100000FemalePopulation: 15.7,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 23,
    causeOfDeath: "การฆ่าตัวตาย ถูกฆ่าตาย",
    year: 2557,
    deathMale: 36,
    deathFemale: 10,
    deathRatePer100000MalePopulation: 11.5,
    deathRatePer100000FemalePopulation: 3.1,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 42,
    causeOfDeath: "เบาหวาน",
    year: 2557,
    deathMale: 41,
    deathFemale: 32,
    deathRatePer100000MalePopulation: 13.1,
    deathRatePer100000FemalePopulation: 10,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 17,
    causeOfDeath: "วัณโรคทุกชนิด",
    year: 2557,
    deathMale: 60,
    deathFemale: 15,
    deathRatePer100000MalePopulation: 19.2,
    deathRatePer100000FemalePopulation: 4.7,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 76,
    causeOfDeath: "โรคภูมิคุ้มกันบกพร่องเนื่องจากไวรัส",
    year: 2557,
    deathMale: 37,
    deathFemale: 21,
    deathRatePer100000MalePopulation: 11.9,
    deathRatePer100000FemalePopulation: 6.6,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 53,
    causeOfDeath: "มะเร็ง และเนื้องอกทุกชนิด",
    year: 2558,
    deathMale: 365,
    deathFemale: 292,
    deathRatePer100000MalePopulation: 116.3,
    deathRatePer100000FemalePopulation: 91.1,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 116,
    causeOfDeath: "อุบัติเหตุจากการขนส่ง",
    year: 2558,
    deathMale: 93,
    deathFemale: 21,
    deathRatePer100000MalePopulation: 29.6,
    deathRatePer100000FemalePopulation: 6.6,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 29,
    causeOfDeath: "ความดันเลือดสูง",
    year: 2558,
    deathMale: 22,
    deathFemale: 26,
    deathRatePer100000MalePopulation: 7,
    deathRatePer100000FemalePopulation: 8.1,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 90,
    causeOfDeath: "โรคหลอดเลือดในสมอง",
    year: 2558,
    deathMale: 205,
    deathFemale: 149,
    deathRatePer100000MalePopulation: 65.3,
    deathRatePer100000FemalePopulation: 46.5,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 93,
    causeOfDeath: "โรคหัวใจขาดเลือด",
    year: 2558,
    deathMale: 158,
    deathFemale: 135,
    deathRatePer100000MalePopulation: 50.3,
    deathRatePer100000FemalePopulation: 42.1,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 48,
    causeOfDeath: "ปอดอักเสบและโรคอื่นๆ ของปอด",
    year: 2558,
    deathMale: 291,
    deathFemale: 179,
    deathRatePer100000MalePopulation: 92.7,
    deathRatePer100000FemalePopulation: 55.9,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 5,
    causeOfDeath: "ไตอักเสบ กลุ่มอาการของไตพิการ และไตพิการ",
    year: 2558,
    deathMale: 65,
    deathFemale: 56,
    deathRatePer100000MalePopulation: 20.7,
    deathRatePer100000FemalePopulation: 17.5,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 10,
    causeOfDeath: "โรคเกี่ยวกับตับและตับอ่อน",
    year: 2558,
    deathMale: 89,
    deathFemale: 43,
    deathRatePer100000MalePopulation: 28.4,
    deathRatePer100000FemalePopulation: 13.4,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 23,
    causeOfDeath: "การฆ่าตัวตาย ถูกฆ่าตาย",
    year: 2558,
    deathMale: 22,
    deathFemale: 11,
    deathRatePer100000MalePopulation: 7,
    deathRatePer100000FemalePopulation: 3.4,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 42,
    causeOfDeath: "เบาหวาน",
    year: 2558,
    deathMale: 20,
    deathFemale: 33,
    deathRatePer100000MalePopulation: 6.4,
    deathRatePer100000FemalePopulation: 10.3,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 17,
    causeOfDeath: "วัณโรคทุกชนิด",
    year: 2558,
    deathMale: 49,
    deathFemale: 16,
    deathRatePer100000MalePopulation: 15.6,
    deathRatePer100000FemalePopulation: 5,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 76,
    causeOfDeath: "โรคภูมิคุ้มกันบกพร่องเนื่องจากไวรัส",
    year: 2558,
    deathMale: 18,
    deathFemale: 13,
    deathRatePer100000MalePopulation: 5.7,
    deathRatePer100000FemalePopulation: 4.1,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 53,
    causeOfDeath: "มะเร็ง และเนื้องอกทุกชนิด",
    year: 2559,
    deathMale: 419,
    deathFemale: 276,
    deathRatePer100000MalePopulation: 132.8,
    deathRatePer100000FemalePopulation: 85.5,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 115,
    causeOfDeath:
      "อุบัติเหตุ เหตุการณ์ที่ไม่สามารถระบุเจตนาและปัจจัยเสริมที่มีความสัมพันธ์กับสาเหตุการตาย",
    year: 2559,
    deathMale: 189,
    deathFemale: 42,
    deathRatePer100000MalePopulation: 59.9,
    deathRatePer100000FemalePopulation: 13,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 3,
    causeOfDeath: "ความดันเลือดสูง และโรคหลอดเลือดในสมอง",
    year: 2559,
    deathMale: 250,
    deathFemale: 197,
    deathRatePer100000MalePopulation: 79.2,
    deathRatePer100000FemalePopulation: 61,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 16,
    causeOfDeath: "โรคหัวใจ",
    year: 2559,
    deathMale: 183,
    deathFemale: 144,
    deathRatePer100000MalePopulation: 58,
    deathRatePer100000FemalePopulation: 44.6,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 48,
    causeOfDeath: "ปอดอักเสบและโรคอื่นๆ ของปอด",
    year: 2559,
    deathMale: 406,
    deathFemale: 278,
    deathRatePer100000MalePopulation: 128.7,
    deathRatePer100000FemalePopulation: 86.1,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 5,
    causeOfDeath: "ไตอักเสบ กลุ่มอาการของไตพิการ และไตพิการ",
    year: 2559,
    deathMale: 61,
    deathFemale: 64,
    deathRatePer100000MalePopulation: 19.3,
    deathRatePer100000FemalePopulation: 19.8,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 10,
    causeOfDeath: "โรคเกี่ยวกับตับและตับอ่อน",
    year: 2559,
    deathMale: 64,
    deathFemale: 43,
    deathRatePer100000MalePopulation: 20.3,
    deathRatePer100000FemalePopulation: 13.3,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 23,
    causeOfDeath: "การฆ่าตัวตาย ถูกฆ่าตาย",
    year: 2559,
    deathMale: 37,
    deathFemale: 9,
    deathRatePer100000MalePopulation: 11.7,
    deathRatePer100000FemalePopulation: 2.8,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 42,
    causeOfDeath: "เบาหวาน",
    year: 2559,
    deathMale: 16,
    deathFemale: 18,
    deathRatePer100000MalePopulation: 5.1,
    deathRatePer100000FemalePopulation: 5.6,
  },
  {
    provinceKey: 19,
    provinceName: "สระบุรี",
    pronvinceNameEng: "Saraburi",
    regionKey: 3,
    region: "ภาคเหนือ",
    regionEng: "Northern",
    diseaseCauseDeathKey: 17,
    causeOfDeath: "วัณโรคทุกชนิด",
    year: 2559,
    deathMale: 36,
    deathFemale: 16,
    deathRatePer100000MalePopulation: 11.4,
    deathRatePer100000FemalePopulation: 5,
  },
];

const Dashboard = (props) => {
  console.log("dashboard", props);
  {console.log("year",props.year)}
  const filterYear = mockData.filter((r) => r.year === props.year);
  const allIllness = filterYear.map((r) => r.causeOfDeath);
  console.log("All illness :", allIllness);
  const uniqueIllness = [...new Set(allIllness)];
  console.log("uniqueIllness :", uniqueIllness);

  const totalDeaths = mockData.reduce(
    (acc, r) => acc + r.deathMale + r.deathFemale,
    0
  );
  console.log("totalDeaths", totalDeaths);

  const sumByDeathCause = (deathLists) =>
    deathLists.reduce((acc, r) => acc + r.deathMale + r.deathFemale, 0);

  const deathByCauses = uniqueIllness
    .map((r, idx) => ({
      name: r,
      totalDeath: sumByDeathCause(mockData.filter((s) => s.causeOfDeath === r)),
    }))
    .sort((a, b) => b.totalDeath - a.totalDeath);
  console.log("deathByCauses: ", deathByCauses);
  const addAll = [
    ...deathByCauses,
    { name: "ทั้งหมด", totalDeath: totalDeaths },
  ].sort((a, b) => b.totalDeath - a.totalDeath);
  console.log("addAll", addAll);

  
  const sumEtc = totalDeaths - addAll.filter((r,idx)=>idx>=1).reduce((acc,r)=>acc+r.totalDeath,0)
  console.log("sumEtc", sumEtc);

  const totalData = [...addAll, { name: "อื่นๆ", totalDeath: sumEtc }].sort(
    (a, b) => b.totalDeath - a.totalDeath
  );
  console.log("totalData:", totalData);

  return (
    <>
      <div className="p-2 border-solid border-2 border-sky-500 ">
        <p>จำนวนผู้เสียชีวิต สาเหตุ และอัตราการตายปี 2554-2559</p>
        <div>เลือกปี:</div>
        <div className="w-screen text-xs border-1 border-solid border-2 border-sky-800">
          <div className="w-1/2 border-1 border-solid border-2 border-sky-800">
           
          </div>
          <DashboardTable data={totalData} totalDeath={totalDeaths} year={(props.year)} />
        </div>
      </div>
    </>
  );
};
export default Dashboard;
