import React from "react";
import mockData from "./thailand-death-cause.json";
const DashBoard1 = () => {
  const Data = [
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 53,
      causeOfDeath: "มะเร็ง และเนื้องอกทุกชนิด",
      year: 2557,
      deathMale: 384,
      deathFemale: 284,
      deathRatePer100000MalePopulation: 123.2,
      deathRatePer100000FemalePopulation: 89.1,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 116,
      causeOfDeath: "อุบัติเหตุจากการขนส่ง",
      year: 2557,
      deathMale: 104,
      deathFemale: 24,
      deathRatePer100000MalePopulation: 33.4,
      deathRatePer100000FemalePopulation: 7.5,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 29,
      causeOfDeath: "ความดันเลือดสูง",
      year: 2557,
      deathMale: 22,
      deathFemale: 28,
      deathRatePer100000MalePopulation: 7.1,
      deathRatePer100000FemalePopulation: 8.8,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 90,
      causeOfDeath: "โรคหลอดเลือดในสมอง",
      year: 2557,
      deathMale: 195,
      deathFemale: 141,
      deathRatePer100000MalePopulation: 62.5,
      deathRatePer100000FemalePopulation: 44.2,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 93,
      causeOfDeath: "โรคหัวใจขาดเลือด",
      year: 2557,
      deathMale: 184,
      deathFemale: 141,
      deathRatePer100000MalePopulation: 59,
      deathRatePer100000FemalePopulation: 44.2,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 48,
      causeOfDeath: "ปอดอักเสบและโรคอื่นๆ ของปอด",
      year: 2557,
      deathMale: 270,
      deathFemale: 200,
      deathRatePer100000MalePopulation: 86.6,
      deathRatePer100000FemalePopulation: 62.7,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 5,
      causeOfDeath: "ไตอักเสบ กลุ่มอาการของไตพิการ และไตพิการ",
      year: 2557,
      deathMale: 57,
      deathFemale: 53,
      deathRatePer100000MalePopulation: 18.3,
      deathRatePer100000FemalePopulation: 16.6,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 10,
      causeOfDeath: "โรคเกี่ยวกับตับและตับอ่อน",
      year: 2557,
      deathMale: 73,
      deathFemale: 50,
      deathRatePer100000MalePopulation: 23.4,
      deathRatePer100000FemalePopulation: 15.7,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 23,
      causeOfDeath: "การฆ่าตัวตาย ถูกฆ่าตาย",
      year: 2557,
      deathMale: 36,
      deathFemale: 10,
      deathRatePer100000MalePopulation: 11.5,
      deathRatePer100000FemalePopulation: 3.1,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 42,
      causeOfDeath: "เบาหวาน",
      year: 2557,
      deathMale: 41,
      deathFemale: 32,
      deathRatePer100000MalePopulation: 13.1,
      deathRatePer100000FemalePopulation: 10,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 17,
      causeOfDeath: "วัณโรคทุกชนิด",
      year: 2557,
      deathMale: 60,
      deathFemale: 15,
      deathRatePer100000MalePopulation: 19.2,
      deathRatePer100000FemalePopulation: 4.7,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 76,
      causeOfDeath: "โรคภูมิคุ้มกันบกพร่องเนื่องจากไวรัส",
      year: 2557,
      deathMale: 37,
      deathFemale: 21,
      deathRatePer100000MalePopulation: 11.9,
      deathRatePer100000FemalePopulation: 6.6,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 53,
      causeOfDeath: "มะเร็ง และเนื้องอกทุกชนิด",
      year: 2558,
      deathMale: 365,
      deathFemale: 292,
      deathRatePer100000MalePopulation: 116.3,
      deathRatePer100000FemalePopulation: 91.1,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 116,
      causeOfDeath: "อุบัติเหตุจากการขนส่ง",
      year: 2558,
      deathMale: 93,
      deathFemale: 21,
      deathRatePer100000MalePopulation: 29.6,
      deathRatePer100000FemalePopulation: 6.6,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 29,
      causeOfDeath: "ความดันเลือดสูง",
      year: 2558,
      deathMale: 22,
      deathFemale: 26,
      deathRatePer100000MalePopulation: 7,
      deathRatePer100000FemalePopulation: 8.1,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 90,
      causeOfDeath: "โรคหลอดเลือดในสมอง",
      year: 2558,
      deathMale: 205,
      deathFemale: 149,
      deathRatePer100000MalePopulation: 65.3,
      deathRatePer100000FemalePopulation: 46.5,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 93,
      causeOfDeath: "โรคหัวใจขาดเลือด",
      year: 2558,
      deathMale: 158,
      deathFemale: 135,
      deathRatePer100000MalePopulation: 50.3,
      deathRatePer100000FemalePopulation: 42.1,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 48,
      causeOfDeath: "ปอดอักเสบและโรคอื่นๆ ของปอด",
      year: 2558,
      deathMale: 291,
      deathFemale: 179,
      deathRatePer100000MalePopulation: 92.7,
      deathRatePer100000FemalePopulation: 55.9,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 5,
      causeOfDeath: "ไตอักเสบ กลุ่มอาการของไตพิการ และไตพิการ",
      year: 2558,
      deathMale: 65,
      deathFemale: 56,
      deathRatePer100000MalePopulation: 20.7,
      deathRatePer100000FemalePopulation: 17.5,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 10,
      causeOfDeath: "โรคเกี่ยวกับตับและตับอ่อน",
      year: 2558,
      deathMale: 89,
      deathFemale: 43,
      deathRatePer100000MalePopulation: 28.4,
      deathRatePer100000FemalePopulation: 13.4,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 23,
      causeOfDeath: "การฆ่าตัวตาย ถูกฆ่าตาย",
      year: 2558,
      deathMale: 22,
      deathFemale: 11,
      deathRatePer100000MalePopulation: 7,
      deathRatePer100000FemalePopulation: 3.4,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 42,
      causeOfDeath: "เบาหวาน",
      year: 2558,
      deathMale: 20,
      deathFemale: 33,
      deathRatePer100000MalePopulation: 6.4,
      deathRatePer100000FemalePopulation: 10.3,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 17,
      causeOfDeath: "วัณโรคทุกชนิด",
      year: 2558,
      deathMale: 49,
      deathFemale: 16,
      deathRatePer100000MalePopulation: 15.6,
      deathRatePer100000FemalePopulation: 5,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 76,
      causeOfDeath: "โรคภูมิคุ้มกันบกพร่องเนื่องจากไวรัส",
      year: 2558,
      deathMale: 18,
      deathFemale: 13,
      deathRatePer100000MalePopulation: 5.7,
      deathRatePer100000FemalePopulation: 4.1,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 53,
      causeOfDeath: "มะเร็ง และเนื้องอกทุกชนิด",
      year: 2559,
      deathMale: 419,
      deathFemale: 276,
      deathRatePer100000MalePopulation: 132.8,
      deathRatePer100000FemalePopulation: 85.5,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 115,
      causeOfDeath:
        "อุบัติเหตุ เหตุการณ์ที่ไม่สามารถระบุเจตนาและปัจจัยเสริมที่มีความสัมพันธ์กับสาเหตุการตาย",
      year: 2559,
      deathMale: 189,
      deathFemale: 42,
      deathRatePer100000MalePopulation: 59.9,
      deathRatePer100000FemalePopulation: 13,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 3,
      causeOfDeath: "ความดันเลือดสูง และโรคหลอดเลือดในสมอง",
      year: 2559,
      deathMale: 250,
      deathFemale: 197,
      deathRatePer100000MalePopulation: 79.2,
      deathRatePer100000FemalePopulation: 61,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 16,
      causeOfDeath: "โรคหัวใจ",
      year: 2559,
      deathMale: 183,
      deathFemale: 144,
      deathRatePer100000MalePopulation: 58,
      deathRatePer100000FemalePopulation: 44.6,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 48,
      causeOfDeath: "ปอดอักเสบและโรคอื่นๆ ของปอด",
      year: 2559,
      deathMale: 406,
      deathFemale: 278,
      deathRatePer100000MalePopulation: 128.7,
      deathRatePer100000FemalePopulation: 86.1,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 5,
      causeOfDeath: "ไตอักเสบ กลุ่มอาการของไตพิการ และไตพิการ",
      year: 2559,
      deathMale: 61,
      deathFemale: 64,
      deathRatePer100000MalePopulation: 19.3,
      deathRatePer100000FemalePopulation: 19.8,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 10,
      causeOfDeath: "โรคเกี่ยวกับตับและตับอ่อน",
      year: 2559,
      deathMale: 64,
      deathFemale: 43,
      deathRatePer100000MalePopulation: 20.3,
      deathRatePer100000FemalePopulation: 13.3,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 23,
      causeOfDeath: "การฆ่าตัวตาย ถูกฆ่าตาย",
      year: 2559,
      deathMale: 37,
      deathFemale: 9,
      deathRatePer100000MalePopulation: 11.7,
      deathRatePer100000FemalePopulation: 2.8,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 42,
      causeOfDeath: "เบาหวาน",
      year: 2559,
      deathMale: 16,
      deathFemale: 18,
      deathRatePer100000MalePopulation: 5.1,
      deathRatePer100000FemalePopulation: 5.6,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 17,
      causeOfDeath: "วัณโรคทุกชนิด",
      year: 2559,
      deathMale: 36,
      deathFemale: 16,
      deathRatePer100000MalePopulation: 11.4,
      deathRatePer100000FemalePopulation: 5,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 76,
      causeOfDeath: "โรคภูมิคุ้มกันบกพร่องเนื่องจากไวรัส",
      year: 2559,
      deathMale: 21,
      deathFemale: 11,
      deathRatePer100000MalePopulation: 6.7,
      deathRatePer100000FemalePopulation: 3.4,
    },
    {
      provinceKey: 19,
      provinceName: "สระบุรี",
      pronvinceNameEng: "Saraburi",
      regionKey: 3,
      region: "ภาคเหนือ",
      regionEng: "Northern",
      diseaseCauseDeathKey: 20,
      causeOfDeath: "อื่นๆ",
      year: 2559,
      deathMale: 532,
      deathFemale: 591,
      deathRatePer100000MalePopulation: 168.6,
      deathRatePer100000FemalePopulation: 183.1,
    },
    {
      provinceKey: 21,
      provinceName: "ระยอง",
      pronvinceNameEng: "Rayong",
      regionKey: 5,
      region: "ภาคใต้",
      regionEng: "Southern",
      diseaseCauseDeathKey: 53,
      causeOfDeath: "มะเร็ง และเนื้องอกทุกชนิด",
      year: 2556,
      deathMale: 282,
      deathFemale: 257,
      deathRatePer100000MalePopulation: 87.4,
      deathRatePer100000FemalePopulation: 77.3,
    },
    {
      provinceKey: 21,
      provinceName: "ระยอง",
      pronvinceNameEng: "Rayong",
      regionKey: 5,
      region: "ภาคใต้",
      regionEng: "Southern",
      diseaseCauseDeathKey: 21,
      causeOfDeath: "อุบัติเหตุ และการเป็นพิษ",
      year: 2556,
      deathMale: 168,
      deathFemale: 54,
      deathRatePer100000MalePopulation: 52,
      deathRatePer100000FemalePopulation: 16.2,
    },
    {
      provinceKey: 21,
      provinceName: "ระยอง",
      pronvinceNameEng: "Rayong",
      regionKey: 5,
      region: "ภาคใต้",
      regionEng: "Southern",
      diseaseCauseDeathKey: 16,
      causeOfDeath: "โรคหัวใจ",
      year: 2556,
      deathMale: 119,
      deathFemale: 103,
      deathRatePer100000MalePopulation: 36.9,
      deathRatePer100000FemalePopulation: 31,
    },
    {
      provinceKey: 21,
      provinceName: "ระยอง",
      pronvinceNameEng: "Rayong",
      regionKey: 5,
      region: "ภาคใต้",
      regionEng: "Southern",
      diseaseCauseDeathKey: 3,
      causeOfDeath: "ความดันเลือดสูง และโรคหลอดเลือดในสมอง",
      year: 2556,
      deathMale: 148,
      deathFemale: 120,
      deathRatePer100000MalePopulation: 45.9,
      deathRatePer100000FemalePopulation: 36.1,
    },
    {
      provinceKey: 21,
      provinceName: "ระยอง",
      pronvinceNameEng: "Rayong",
      regionKey: 5,
      region: "ภาคใต้",
      regionEng: "Southern",
      diseaseCauseDeathKey: 48,
      causeOfDeath: "ปอดอักเสบและโรคอื่นๆ ของปอด",
      year: 2556,
      deathMale: 134,
      deathFemale: 75,
      deathRatePer100000MalePopulation: 41.5,
      deathRatePer100000FemalePopulation: 22.6,
    },
  ];

  const overallTotalDeath = mockData.reduce(
    (acc, r) => acc + r.deathMale + r.deathFemale,
    0
  );

  const causeOfDeathList = [...new Set(mockData.map((r) => r.causeOfDeath))]; //[เบาหวาน ถูกฆ่า]
  console.log("list:", causeOfDeathList);

  const deathByCauses = causeOfDeathList.map((cause) => {
    const filterData = mockData.filter((r) => r.causeOfDeath === cause);
    console.log("filter", filterData);
    const totalDeath = filterData.reduce(
      (acc, r) => {
        acc.deathMale += r.deathMale;
        acc.deathFemale += r.deathFemale;

        return acc;
      },
      { deathMale: 0, deathFemale: 0 }
    );
    console.log("total1", totalDeath);
    // return totalDeath;
    return {
      deathCause: cause,
      deathFemale: totalDeath.deathFemale,
      deathMale: totalDeath.deathMale,
      totalDeath: totalDeath.deathFemale + totalDeath.deathMale,
      percentage:
        (((totalDeath.deathFemale + totalDeath.deathMale) / overallTotalDeath) *
        100).toFixed(2),
    };
  });

  const deathNumberSorted = deathByCauses.sort(
    (a, b) => b.totalDeath - a.totalDeath
  );

  const deathByProvinceList = [...new Set(mockData.map((r) => r.provinceName))];
  console.log("province list:", deathByProvinceList);

  const deathByProvince = deathByProvinceList.map((province) => {
    const filteredProvince = mockData.filter(
      (r) => r.provinceName === province
    );
    console.log("province filtered:", filteredProvince);
    const totalDeathByProvince = filteredProvince.reduce(
      (acc, r) => {
        acc.deathMale += r.deathMale;
        acc.deathFemale += r.deathFemale;

        return acc;
      },
      { deathMale: 0, deathFemale: 0 }
    );
    console.log("total2", totalDeathByProvince);
    return {
      provinces: province,
      totalDeath:
        totalDeathByProvince.deathFemale + totalDeathByProvince.deathMale,
      percentage:
        (((totalDeathByProvince.deathFemale + totalDeathByProvince.deathMale) /
          overallTotalDeath) *
        100).toFixed(2),
    };
  });
  const numberProvinceSorted = deathByProvince.sort(
    (a, b) => b.totalDeathByProvince - a.totalDeathByProvince
  );
  // console.log("sorted2", deathNumberSorted2);
  return (
    <table className="table table-fixed border border-2 border-red">
      <h1 className="text-xl font-bold p-2">
        จำนวนผู้เสียชีวิต สาเหตุ และอัตราการตาย ปี 2554 - 2559
      </h1>
      <tbody className="flex p-2">
        <tr className=" table table-fixed border border-2 border-red">
          {deathNumberSorted.map((r) => (
            <tr className="flex m-3">
              <td className="w-44">{r.deathCause}</td>
              <td className="ml-2 w-24">{r.totalDeath}</td>
              <td className="ml-2">{r.percentage} %</td>
            </tr>
          ))}
        </tr>
        <tr className=" table table-fixed border border-2 border-red">
          {numberProvinceSorted.map((r) => (
            <tr className="flex m-3">
              <td className="w-44">{r.provinces} </td>
              <td className="ml-2 w-24">{r.totalDeath}</td>
              <td className="ml-2">{r.percentage} %</td>
            </tr>
          ))}
        </tr>
      </tbody>
    </table>
  );
};

export default DashBoard1;
