export * from "./useSelectedCause"
export * from "./useTotalDeath"
export * from "./useDeathByCause"
export * from "./useDeathByProvince"
export * from "./useChartOption1"
export * from "./useChartOption2"